version: "2"
plugins:
  brakeman:
    enabled: true
  rubocop:
    enabled: true
  eslint:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
  fixme:
    enabled: true
  rubocop:
    enabled: true
    channel: rubocop-0-73
exclude_patterns:
exclude_patterns:
- db/*
- spec/*
- tests/*
- vendor/*
- .gems/

# examples of third party libraries that should be excluded
- */jquery/*
- */bootstrap/*

# examples of minified files that should be excluded
- **.min.js
- **.min.css