require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/*.rb'
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - '.gems/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'scripts/template.rb'
    - 'bin/*'
    - 'node_modules/**/*'
Rails:
  Enabled: true
Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/IndentFirstArgument:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
